# Generated by Django 4.2 on 2023-05-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_name_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentClub',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club'),
        ),
    ]
