# Generated by Django 4.2 on 2023-05-02 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_drill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.challenge')),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='challenges',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.level_challenge')),
            ],
        ),
        migrations.AddField(
            model_name='level_challenge',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.level'),
        ),
        migrations.CreateModel(
            name='Drill_Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repetition', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('endTime', models.TimeField(blank=True, default=0, null=True)),
                ('numberOfDrill', models.PositiveIntegerField(default=1)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drill')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.program')),
            ],
        ),
    ]
