# Generated by Django 4.2 on 2023-05-05 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('drills', '0003_level_challenge_remove_level_challenges_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.CreateModel(
            name='Finished_Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numberOfTries', models.IntegerField(default=1)),
                ('highScoreQuantity', models.IntegerField()),
                ('highScoreTime', models.TimeField()),
                ('highScoreDate', models.DateTimeField()),
                ('lastTryDate', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.program')),
            ],
        ),
    ]
