# Generated by Django 4.2 on 2023-05-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_currentclub_alter_profile_user'),
        ('drills', '0004_program_owner_finished_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drill_Exercise',
            new_name='DrillExercise',
        ),
        migrations.RenameModel(
            old_name='Finished_Program',
            new_name='FinishedProgram',
        ),
        migrations.RenameModel(
            old_name='Level_Challenge',
            new_name='LevelChallenge',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='level_challenge',
            new_name='levelchallenge',
        ),
    ]
