# Generated by Django 4.2 on 2023-05-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_currentclub_alter_profile_user'),
        ('drills', '0005_rename_drill_exercise_drillexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
