# Generated by Django 4.2 on 2023-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0006_alter_program_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drillexercise',
            options={'ordering': ['numberOfDrill']},
        ),
        migrations.AlterField(
            model_name='finishedprogram',
            name='lastTryDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
