# Generated by Django 4.2 on 2023-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0007_alter_drillexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedprogram',
            name='highScoreTime',
            field=models.IntegerField(),
        ),
    ]
