# Generated by Django 4.2 on 2023-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0008_alter_finishedprogram_highscoretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedprogram',
            name='highScoreDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finishedprogram',
            name='highScoreQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finishedprogram',
            name='highScoreTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
