# Generated by Django 4.2 on 2023-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0009_alter_finishedprogram_highscoredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillexercise',
            name='endTime',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
