# Generated by Django 4.2 on 2023-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0010_alter_drillexercise_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.TextField(choices=[('Reaction', 'Reaction'), ('BallHandling', 'BallHandling'), ('Agility', 'Agility')], default=('BallHandling', 'BallHandling'), max_length=50),
        ),
    ]
