# Generated by Django 4.2 on 2023-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0011_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.TextField(choices=[('Reaction', 'Reaction'), ('BallHandling', 'BallHandling'), ('Agility', 'Agility')], max_length=50),
        ),
    ]
